# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
#       http://doc.scrapy.org/en/latest/topics/items.html

from scrapy.item import Item, Field

class IPItem(Item):
    status = Field()
    date = Field()
    lat = Field()
    lon = Field()
    timezone = Field()
    org = Field()

class ProxyItem(Item):
    status = Field()
    date = Field()
    ip = Field()

class PropertyItem(Item):
	vendor = Field()
	type = Field()
	created_date = Field()
	last_crawled_date = Field()
	last_indexed_date = Field()
	property_id = Field()
	link = Field()
	listing_type = Field()
	property_size_raw = Field()
	property_size = Field()
	property_size_unit = Field()
	property_price_raw = Field()
	property_price = Field()
	property_price_unit = Field()
	property_area = Field()
	posted_date = Field()

class HouseItem(Item):
	key = Field()
	vendor = Field()
	type = Field()
	property_id = Field()
	link = Field()
	crawled_date = Field()
	posted_date = Field()
	expire_date = Field()
	title = Field()
	description = Field()
	address = Field()
	area = Field()
	ward = Field()
	district = Field()
	city = Field()
	price_raw = Field()
	price = Field()
	price_unit = Field()
	price_per_sqm = Field()
	property_size_raw = Field()
	property_size = Field()
	property_size_unit = Field()
	distance_to_road = Field()
	frontage = Field()
	ownership_certificate = Field()
	road_width = Field()
	num_floors = Field()
	num_bedrooms = Field()
	num_bathrooms = Field()
	house_orientation = Field()
	balcony_orientation = Field()
	furniture = Field()
	images = Field()
	videos = Field()
	listing_type = Field()
	contact_name = Field()
	contact_address = Field()
	contact_phone = Field()
	contact_mobile = Field()
	contact_email = Field()
	contact_link = Field()
	project_name = Field()
	project_owner = Field()
	project_scale = Field()
	project_link = Field()
